#!/usr/bin/env -S deno run -A

/**
 * Git hooks installation entrypoint
 *
 * This module provides functionality to install git hooks from your configuration.
 * It can be used as a CLI script or imported programmatically.
 *
 * @example CLI usage
 * ```bash
 * deno run -A jsr:@theswanfactory/deno-hooks/install
 * ```
 *
 * @example Programmatic usage
 * ```ts
 * import { install } from "@theswanfactory/deno-hooks/install";
 * await install();
 * ```
 *
 * @module
 */

import { ensureDir } from "@std/fs";
import { loadConfig } from "./config.ts";
import { getGitRoot } from "./files.ts";

/**
 * Install git hooks based on the project configuration
 *
 * This function:
 * 1. Validates that configuration exists (deno-hooks.yml or deno.json)
 * 2. Creates .git/hooks/ directory if needed
 * 3. Generates shell wrapper scripts for each configured hook
 * 4. Makes scripts executable (Unix/Linux/macOS)
 *
 * @throws {Error} If not in a git repository
 * @throws {Error} If no configuration found
 * @throws {Error} If configuration is invalid
 *
 * @example
 * ```ts
 * import { install } from "@theswanfactory/deno-hooks";
 *
 * await install();
 * ```
 */
export async function install(): Promise<void> {
  console.log("🦕 Installing Deno Hooks...\n");

  // Get git root
  const gitRoot = await getGitRoot();
  console.log(`📁 Git root: ${gitRoot}`);

  // Load and validate configuration
  const config = await loadConfig(gitRoot);
  const hookNames = Object.keys(config.hooks);
  console.log(`📋 Found ${hookNames.length} hook(s): ${hookNames.join(", ")}`);

  // Ensure .git/hooks/ exists
  const hooksDir = `${gitRoot}/.git/hooks`;
  await ensureDir(hooksDir);

  // Install each hook
  for (const hookName of hookNames) {
    await installHook(hooksDir, hookName);
  }

  console.log("\n✅ Installation complete!");
  console.log("\nGit hooks are now active. They will run automatically on:");
  for (const hookName of hookNames) {
    console.log(`  - ${hookName}`);
  }
}

/**
 * Install a single git hook
 */
async function installHook(
  hooksDir: string,
  hookName: string,
): Promise<void> {
  const hookPath = `${hooksDir}/${hookName}`;

  // Generate shell script
  const script = generateHookScript(hookName);

  // Write script
  await Deno.writeTextFile(hookPath, script);

  // Make executable (Unix only - Windows uses git's shell)
  if (Deno.build.os !== "windows") {
    await Deno.chmod(hookPath, 0o755);
  }

  console.log(`  ✓ Installed ${hookName}`);
}

/**
 * Generate shell wrapper script for a hook
 */
function generateHookScript(hookName: string): string {
  // Use #!/bin/sh for maximum portability
  // Use import.meta.resolve to get the path to run.ts in the installed package
  const runScriptPath = new URL("./run.ts", import.meta.url).pathname;
  return `#!/bin/sh
# Generated by deno-hooks - DO NOT EDIT
# To update, run: deno task setup

exec deno run -A "${runScriptPath}" "${hookName}" "$@"
`;
}

// Run if called directly
if (import.meta.main) {
  try {
    await install();
  } catch (error) {
    console.error(
      "\n❌ Installation failed:",
      error instanceof Error ? error.message : String(error),
    );
    Deno.exit(1);
  }
}
