#!/usr/bin/env -S deno run -A

/**
 * Git hooks installation entrypoint
 *
 * This module provides functionality to install git hooks from your configuration.
 * It can be used as a CLI script or imported programmatically.
 *
 * @example CLI usage
 * ```bash
 * deno run -A jsr:@theswanfactory/deno-hooks/install
 * ```
 *
 * @example Programmatic usage
 * ```ts
 * import { install } from "@theswanfactory/deno-hooks/install";
 * await install();
 * ```
 *
 * @module
 */

import { ensureDir } from "@std/fs";
import { loadConfig } from "./config.ts";
import { getGitRoot } from "./files.ts";

/**
 * Install git hooks based on the project configuration
 *
 * This function:
 * 1. Validates that configuration exists (deno-hooks.yml or deno.json)
 * 2. Creates .git/hooks/ directory if needed
 * 3. Generates shell wrapper scripts for each configured hook
 * 4. Makes scripts executable (Unix/Linux/macOS)
 *
 * @throws {Error} If not in a git repository
 * @throws {Error} If no configuration found
 * @throws {Error} If configuration is invalid
 *
 * @example
 * ```ts
 * import { install } from "@theswanfactory/deno-hooks";
 *
 * await install();
 * ```
 */
export async function install(): Promise<void> {
  console.log("🦕 Installing Deno Hooks...\n");

  // Get git root
  const gitRoot = await getGitRoot();
  console.log(`📁 Git root: ${gitRoot}`);

  // Check if config exists, offer to create default
  let config;
  try {
    config = await loadConfig(gitRoot);
  } catch (error) {
    if (error instanceof Error && error.message.includes("not found")) {
      const shouldCreate = promptCreateDefaultConfig();
      if (shouldCreate) {
        await createDefaultConfig(gitRoot);
        config = await loadConfig(gitRoot);
        console.log("\n✅ Created deno-hooks.yml with default configuration");
      } else {
        throw new Error(
          "No configuration found. Create deno-hooks.yml or add configuration to deno.json",
        );
      }
    } else {
      throw error;
    }
  }

  const hookNames = Object.keys(config.hooks);

  // Show what hooks will be installed
  console.log(`\n📋 Installing ${hookNames.length} hook(s):\n`);
  for (const hookName of hookNames) {
    const hooks = config.hooks[hookName];
    console.log(`${hookName}:`);
    for (const hook of hooks) {
      const displayName = hook.name || hook.id;
      console.log(`  - ${displayName}`);
    }
  }

  // Ensure .git/hooks/ exists
  const hooksDir = `${gitRoot}/.git/hooks`;
  await ensureDir(hooksDir);

  // Install each hook
  console.log();
  for (const hookName of hookNames) {
    await installHook(hooksDir, hookName);
  }

  console.log("\n✅ Installation complete!");
  console.log("\nHooks will run automatically on commit/push.");
  console.log("To customize, edit deno-hooks.yml in your project root.");
}

/**
 * Install a single git hook
 */
async function installHook(
  hooksDir: string,
  hookName: string,
): Promise<void> {
  const hookPath = `${hooksDir}/${hookName}`;

  // Generate shell script
  const script = generateHookScript(hookName);

  // Write script
  await Deno.writeTextFile(hookPath, script);

  // Make executable (Unix only - Windows uses git's shell)
  if (Deno.build.os !== "windows") {
    await Deno.chmod(hookPath, 0o755);
  }

  console.log(`  ✓ Installed ${hookName}`);
}

/**
 * Generate shell wrapper script for a hook
 */
function generateHookScript(hookName: string): string {
  // Use #!/bin/sh for maximum portability
  // Detect if we're running from JSR or local filesystem
  const isJSR = import.meta.url.startsWith("jsr:");

  let runScriptPath: string;
  if (isJSR) {
    // For JSR installations, preserve the full JSR specifier (jsr:@scope/package@version/path)
    runScriptPath = new URL("./run.ts", import.meta.url).href;
  } else {
    // For local filesystem, use pathname to get absolute file path
    runScriptPath = new URL("./run.ts", import.meta.url).pathname;
  }

  return `#!/bin/sh
# Generated by deno-hooks - DO NOT EDIT
# To update, run: deno task setup

exec deno run -A "${runScriptPath}" "${hookName}" "$@"
`;
}

/**
 * Prompt user to create default configuration
 */
function promptCreateDefaultConfig(): boolean {
  console.log("\n⚠️  No configuration file found");
  console.log(
    "\nWould you like to create a default deno-hooks.yml with basic hooks?",
  );
  console.log("  - pre-commit: deno fmt, deno lint");
  console.log("  - pre-push: deno test");

  const response = prompt("\nCreate default configuration? [Y/n]");
  return !response || response.toLowerCase() === "y" ||
    response.toLowerCase() === "yes";
}

/**
 * Create default configuration file
 */
async function createDefaultConfig(gitRoot: string): Promise<void> {
  const defaultConfig = `# Deno Hooks Configuration
# Learn more: https://jsr.io/@theswanfactory/deno-hooks

hooks:
  pre-commit:
    # Format code automatically
    - id: deno-fmt
      run: deno-fmt
      glob: "*.{ts,js,json,md}"
      pass_filenames: true

    # Catch common errors
    - id: deno-lint
      run: deno-lint
      glob: "*.{ts,js}"
      pass_filenames: true

  pre-push:
    # Run tests before pushing
    - id: deno-test
      run: deno-test
      pass_filenames: false
`;

  const configPath = `${gitRoot}/deno-hooks.yml`;
  await Deno.writeTextFile(configPath, defaultConfig);
}

// Run if called directly
if (import.meta.main) {
  try {
    await install();
  } catch (error) {
    console.error(
      "\n❌ Installation failed:",
      error instanceof Error ? error.message : String(error),
    );
    Deno.exit(1);
  }
}
